### ISSUE TITLE
ironclust vs JRCLUST?

### ISSUE THREAD

**Issue by kouichi-c-nakamura** [jamesjun/ironclust#26]
What is the difference and relationship between ironclust and JRCLUST ? Neither the [Readme](https://github.com/jamesjun/ironclust/blob/master/matlab/readme.md) nor [Wiki](https://github.com/jamesjun/ironclust/wiki) explains this basic question.

The documentation for ironclust is very limited, but can I refer to [the JRCLUST documentation](https://jrclust.readthedocs.io/en/latest/index.html) instead? I managed to run through the steps in [the tutorial](https://github.com/jamesjun/ironclust/wiki/Tutorial), but now I'm wondering how other people managed to use this tool.

**Comment by jamesjun** [comment]
Thanks for your interest Kouichi and I apologize for your frustration. I initially developed JRClust and I am continuing the development of IronClust since I joined Flatiron Institute. JRClust is currently maintained by Alan Liddell from Vidrio Technologies. 

IronClust and JRClust interfaces are similar but IronClust has a few added features such as drift clustering view in the manual interface. I will update the documentation ASAP. Yes, you may refer to the JRClust documentation for the manual clustering. 

The largest difference is how IronClust handles drift and the clustering method. IronClust uses anatomical similarity to define a local neighborhood and applies clustering by using a fixed neighborhood size. JRClust uses temporally close events to define a local neighborhood and uses the original Rodriguez-Laio clustering (DPCLUS). IronClust uses a modified version of DPCLUS based on KNN that can deal better with heterogenous cluster sizes. I am actively working on a manuscript and will post a bioRxiv paper soon. 

-James

**Comment by jamesjun** [comment]
One useful trick is press ‘h’ to display help in the user interfaces. 

-James

**Comment by kouichi-c-nakamura** [comment]
Thank you for clarifying the matter.

They're both your creation and hence similar. But IronClust is newer and has some improvements. Meanwhile, for most of the things, we can refer to JRClust documentation.

This is what I got. Cheers!

**Comment by kouichi-c-nakamura** [comment]
I've just closed the issue, but I'd like to add one thing.

Before writing massive documentation, just upload the screenshots of the demo code in Wiki or for README. At least, they'll inspire people!

Kouichi
